// Generated by nest CLI- nest generate controller messages/messages --flat
// Body and param decorators are used to extract the body and parameters from the request.
import { Controller, Get, Post, Body, Param } from '@nestjs/common';
import { CreateMessageDto } from './dtos/create-message.dto';

// This @Controller is a CLASS DECORATOR.
@Controller('/messages')
export class MessagesController {
  // This @Get() is a method decorator.
  @Get()
  listMessages() {
    return 'Get 1 blah';
  }

  // This @Post() is a METHOD DECORATOR.
  @Post()
  // This @Body() is a ARGUMENT DECORATOR.
  createMessage(@Body() payload: CreateMessageDto) {
    console.log(payload);
  }

  @Get('/:id')
  // This @Param() is a ARGUMENT DECORATOR.
  getMessage(@Param('id') id: string) {
    console.log(id);
  }
}
