// Generated by nest CLI- nest generate controller messages/messages --flat
import { Controller, Get, Post } from '@nestjs/common';

@Controller('/messages')
export class MessagesController {
  @Get()
  listMessages() {
    return 'Get 1 blah';
  }

  @Post()
  createMessage() {
    return 'Post blah';
  }

  @Get('/:id')
  getMessage() {
    return 'Get 2 blah';
  }
}
